### ISSUE TITLE
what needs fixing

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityForumFixer#1]
some initial todo list

# TODO
- [x] BUG: replies and views in wrong order, Replies first (and bigger text) then views below it (like old forum)
- [x] BUG: post preview tooltip doesnt disappear on other pages sometimes
- [x] BUG: topics view, wrong name for OP poster, sometimes?
- [x] BUG: joined date displayed in hours, due to timer adjust code https://discussions.unity.com/u/mgear/summary
- [x] BUG: main page is broken, due to custom css https://discussions.unity.com/
- [ ] show visited threads with different color!!! *how is it even possible that it doesnt have "visited" color for links > <
- [x] add asset store link at top and open in new tab by default
- [x] Remove big welcome title (to give more space to forums)
- [x] move searchbar to top right (to give more space to forums)
- [x] remove that huge 1.1mb png background banner image ([link](https://cdck-file-uploads-europe1.s3.dualstack.eu-west-1.amazonaws.com/unitymigration/original/4X/0/7/d/07d8efa1f31532aeef11bda3c184cf424bf394d3.png)) 
- [x] hide, move or make this banner smaller: "try the product areas > or filter topics via ...."
- [x] make left bar rows more compact, so that no need to scroll so much (and can hide some rows)
- [x] adjust "see 4 new or updated topics", it feels like it blocks the post title below, and has weird colors (and too tall div)
- [x] latest posts view:  show original poster name and show last poster username below time and topic post time
- [x] move new topic button to right side (since you are constantly scrolling with right edge scrollbar already)
- [x] hide or make post tags/category smaller "unity engine 2022-3-LTS Beginner Bug Universal-Render-Pipeline macOS-Editor visionOS" (in latest/ view) and hide unity engine icon on that row also
- [x] hide views eye icon (add "views" header title instead), same for replies icon and title (or combine them both into same cell
- [ ] adjust fonts and colors everywhere
- [x] remove rounding *might want to keep rounding for user icons later, lets see
- [x] search dropdown fixes (font size, hover color)
- [x] hide or move big "unresolved" text (right at the front of post title)
- [x] posts list, activity: change last post time: "10m" into "10 minutes ago" (10 meters ago looks strange..: ) *problem: some script updates that value every minute? (so need to poll or update values every minute then?)
- [x] make whole site less wide (looks too wide on regular monitor)
- [ ] make latest posts table colors less busy
- [ ] disable custom scrollbar colors (cannot see scrollbar background at all in dark mode now..)
- [ ] improve Create New topic panel (hard to see where it ends and starts..) and its way too small, need to scroll right away just to start typing
- [x] improve Create new topic dropdown: fonts and colors hard to read (all bright white on dark bg and very close to eachother and subtitle is also same bright white)
- [ ] post view: add missing tooltip to that bell icon, not sure what it does yet
- [ ] post view: make "start composing reply" button blue, like regular reply buttons, now it looks disabled
- [ ] post view: move appearing post title panel down or make it smaller, now it blocks global top links bar
- [x] post view: move username above the user icon
- [ ] post view: move view count below the original post to somewhere else (why is it even there as own panel row..)
- [ ] post view: show full timestamp for post "sep 2023" --> "title="Sep 16, 2023 4:33 pm" *and make it customizable, so you can see proper date-time "16 September 2023 16:33" or so
- [x] post view: remove " New & Unread Topics" area completely
- [ ] post view: remove or make the global footer much smaller (if you press end key, you are not seeing last post but just these extra fillers..)
- [ ] left panel: fix minimized left panel (unity forum logo is cropped out)
- [ ] left panel: add links to "your posts" and "bookmarks" in maximized view also (now its only in minimized panel?)
- [ ] left panel: make mini/maximize animation much faster
- [ ] top bar: make all links open in new tab (instead of taking you out from the forum)
- [x] notifications: make "dismiss" button close that notification panel
- [x] notifications: move dismiss button at the top?
- [x] notifications dropdown: "new post" icon doesnt make sense.. what is it? maybe replace all icons with text. "bobby replied to ...", "boddy liked ...."
- [x] latest posts view: add mouseover color to each row, or at least post title
- [ ] top bar mouse hover color appears too slowly
- [ ] add tooltips to tags (below post title)
- [ ] add some new topic highlight or color (the small blue dot is not noticeable)
- [ ] align top bar items with forum content left side
- [ ] combine searchbox, areas and new topic button into same row
- [ ] "you have 1 unread post in this thread", make that icon more visible (if its useful icon)
- [x] remove box from tags (below post title), probably looks better without box outline?
- [ ] "question" tag color is brown.. use some other color, or hide question tag, doesnt seem useful if most posts are questions? (and others dont just have the question tag assigned, even if its question)
- [ ] sidebar: rename "my posts" into "my post & drafts" (since it seems to go into "my unposted drafts"?)
- [ ] sidebar: make scrollbar always visible (annoying when its invisible, you think that there is nothing below?)
- [ ] post view: hide emoji tooltip faster when mouse hover ends in thumb
- [ ] post view: make post bottom reply button blue or otherwise active color
- [ ] post view: add hover color in the time scroll area (so can see which area is draggable)
- [x] latest posts view: could combine replies and views columns, single column replies: 12, views: 200 below it as smaller
- [x] latest posts view: remove hot topic orange highlight, doesnt make sense to highlight it 10yr old topic has +10k views
- [x] limit user signature height (for example 32px and clip extras)
- [x] make notifications dropdown appear on mouse over (instead of having to click)
- [ ] add follow topic button above the original post (not at the bottom of whole thread like its now)
- [ ] add tool tips for vote up and down buttons
- [ ] post view: show last edited date
- [ ] sort unity version tags dropdown in some better order (now some old 2017 is at the top..)
- [ ] posts, code view area: make copy & full screen buttons always visible
- [ ] posts, code view area: use better font or colors? or alternate colors per line *Now uses Fira Code, if available
- [ ] posts: add horizontal line after post area (to separate those buttons for like, reply..)
- [ ] cannot triple click in all textboxes,m to select all text (like when adding custom links..), override that to fix?
- [ ] add new link dialog, delete button is on wrong side, add to left corner
- [ ] hide the loading bar! (was added recently, if you refresh latest posts page, it shows loading bar animation!)
- [x] unity forum bug: red unpin button doesnt work, (they are looking into it past several weeks..) it needs put: https://discussions.unity.com/t/1589244/clear-pin to clear per post
- [ ] add tooltip for user icons in discussion view
- [ ] add link to username in topics view (so that can click username if needed)

### New Features
- [x] maybe can add mouse over preview for last forum post (if possible to fetch)
- [ ] check if can make the forum post time scroll realtime (that no need to release mouse every click)
- [x] check if can show user joined date & post count under username box in posts view *can, but requires fetching JSON file Per user.. (so it only fetches 3 users now)
- [ ] "page not found" add direct link to web archive for old forum threads (that were not imported to new forum)
- [ ] paginated views would be nice: So apparently crawlers get paginated views, but users get that annoying infinity scroller : D https://discussions.unity.com/t/update-about-the-future-of-the-unity-forums-and-unity-discussions/950842/887
~~- [ ] test: notifications panel could be always open? so no need to click it..~~
- [x] mouseover tooltip preview for notification topics (saves time for opening to check what it was about)
- [ ] new topic: unity version, show previously used value at top (or as quicklink)

**Comment by MauriceHandwerker** [comment]
pls add a dark mode ^^

**Comment by unitycoder** [comment]
> pls add a dark mode ^^

Forum does have dark mode and most features here should work there as is!

* oh, looks like tooltip doesnt look good in dark mode
** Fixed
